"""empty message

Revision ID: 4ab148afae72
Revises: b789e6402eec
Create Date: 2016-07-22 16:03:01.601084

"""

# revision identifiers, used by Alembic.
revision = '4ab148afae72'
down_revision = 'b789e6402eec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    ### end Alembic commands ###
