"""empty message

Revision ID: 66cf66a6d4e2
Revises: 4ab148afae72
Create Date: 2016-07-22 17:53:02.781055

"""

# revision identifiers, used by Alembic.
revision = '66cf66a6d4e2'
down_revision = '4ab148afae72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
