"""empty message

Revision ID: b789e6402eec
Revises: e53049e78ea3
Create Date: 2016-07-22 15:59:36.144247

"""

# revision identifiers, used by Alembic.
revision = 'b789e6402eec'
down_revision = 'e53049e78ea3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
