"""empty message

Revision ID: fba104753a11
Revises: 66cf66a6d4e2
Create Date: 2016-07-22 17:57:53.309885

"""

# revision identifiers, used by Alembic.
revision = 'fba104753a11'
down_revision = '66cf66a6d4e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    ### end Alembic commands ###
